CREATE DATABASE [DBAReports]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAReports', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.BROISSWDEV\MSSQL\DATA\DBAReports.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBAReports_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.BROISSWDEV\MSSQL\DATA\DBAReports_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DBAReports] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [DBAReports] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBAReports] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBAReports] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBAReports] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBAReports] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBAReports] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBAReports] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBAReports] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [DBAReports] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBAReports] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBAReports] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBAReports] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBAReports] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBAReports] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBAReports] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBAReports] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBAReports] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBAReports] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBAReports] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBAReports] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBAReports] SET  READ_WRITE 
GO
ALTER DATABASE [DBAReports] SET RECOVERY FULL 
GO
ALTER DATABASE [DBAReports] SET  MULTI_USER 
GO
ALTER DATABASE [DBAReports] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBAReports] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBAReports] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DBAReports]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [DBAReports]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DBAReports] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
